import { useEffect } from 'react'
import Head from 'next/head'
import { useRouter } from 'next/router'
import AppLayout from 'components/AppLayout'
import Button from 'components/Button'
import Github from 'components/Icons/Github'
import { colors } from '../styles/theme'
import { loginWithGithub } from '../services/firebase'
import Avatar from '../components/Avatar'
import useUser from 'hooks/useUser'
import { Routes } from 'data/routes'

export default function Home() {
  const router = useRouter()
  const user = useUser()
  const onHandleClick = () => {
    loginWithGithub().catch((err) => console.log(err))
  }

  useEffect(() => {
    user && router.replace(Routes.HOME)
  }, [user])

  return (
    <>
      <Head>
        <title>Prueba Nextjs</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <AppLayout>
        <section>
          <img src='/logo.jpg' alt='logo' />
          <h1>Devter</h1>
          <h2>Talk about development with developers 👨‍💻 👩‍💻 </h2>
          {user === null && (
            <Button onClick={onHandleClick}>
              <Github fill='#fff' /> Login with github
            </Button>
          )}

          {user && user.avatar && (
            <div>
              <Avatar
                source={user.avatar}
                size={32}
                alt='avatar'
                text={user.email}
                isWithText
              />
            </div>
          )}
          {user === undefined && <span>Cargando...</span>}
        </section>
      </AppLayout>
      <style jsx>{`
        section {
          display: flex;
          justify-content: center;
          align-items: center;
          flex-direction: column;
          height: 100%;
        }
        img {
          height: 60px;
          width: 60px;
          object-fit: contain;
        }
        h1 {
          color: ${colors.primary};
          margin-top: 18px;
          margin-bottom: 4.5px;
          font-weight: 800;
        }
        h2 {
          color: ${colors.secondary};
          font-size: 16px;
          margin-bottom: 9px;
        }
      `}</style>
    </>
  )
}
